1
kompasvideo/java-explore-with-me pull request #1
Opened 2022-10-09 13:42 UTC by kompasvideo

2022-10-10 11:14 UTC, eugene-lenkevich requested changes
Привет, Андрей, спасибо за PR

Первым делом поздравляю тебя с тем, что ты дошел до дипломной работы, ты крут без вариантов :)

Далее, наша цель в том, чтобы сделать красоту в этом проекте, все таки диплом, вдруг по нему оценивать навыки будут.  Я оставил кучку коментариев, будут вопросы, задавай в слаке, не стесняйся, немножко допилить осталось :)

Удачи!

2022-10-10 11:14 UTC, eugene-lenkevich commented on main-service/src/main/java/ru/practicum/explorewithme/main/event/model/AdminUpdateEventDto.java
> +    @JsonSerialize(using = LocalDateTimeSerializer.class)
Давай попробуем настроить фоматы даты и времени глобально, чтобы не приходилось вот так везде аннотациями это указывать :)

https://www.baeldung.com/spring-boot-formatting-json-dates

2022-10-10 11:14 UTC, eugene-lenkevich commented on main-service/src/main/java/ru/practicum/explorewithme/main/request/RequestServiceImpl.java
> +        userRepository.findById(userId).orElseThrow(() -> new NotFoundException(userId.toString()));
В подобных местах наверно тоже лучше использовать existsById, в итоге будет сгенерирован гораздо более легкий запрос, чем поиск и извлечение сущности (а есди у нее еще и связи есть... =)

2022-10-10 11:14 UTC, eugene-lenkevich commented on main-service/src/main/java/ru/practicum/explorewithme/main/request/RequestRepository.java
> +    Boolean existsByEventIdAndUserId(Long userId, Long eventId);
Опять таки, давай попробуем обойтись без @Query

2022-10-10 11:14 UTC, eugene-lenkevich commented on stat-module/src/main/java/ru/practicum/explorewithme/statmodule/ClientStat.java
> +        HttpEntity<StatData> httpEntity = new HttpEntity<>(StatData.builder()
Вот тут есть моментик, который можно улучшить :)
 
В самом клиенте происходит создание и настройка web-клинента. С архитектурной точки зрения это не очень хорошо, клиент занимается своей настройкой, это не его обязаность. Настройку лучше вынести вовне. Можно сделать конфигурацию для бина web-clients и далее он, настроенный, будет инжектится как и остальные бины.

Единственное, аннотацию @Service надо убрать, вообще, это алтьернативный способ объявления бинов: мы можем на класс повесить аннотацию или создать такую вот конфигурацию если требуется провести какую то настройку при создании 

Пример вот, только подправь под свою реализацию

![image](https://user-images.githubusercontent.com/94845100/193436606-1894b4f9-aa6d-4359-adec-0791cef7a4e6.png)

Таким образом мы можем иметь разные настройки клиентов для разных сред: допустим на продакшн-сервере с TLS, сертификатами и пр, на тестововм стенде простое соединение, а для локального запуска мы можем, например, вообще создать заглушку, которая будет возвращать статический текст :)


https://www.baeldung.com/spring-profiles

2022-10-10 11:14 UTC, eugene-lenkevich commented on stat-service/src/main/java/ru/practicum/explorewithme/stat/StatService.java
> +    public ModelMapper modelMapper() {
Давай лучше в отдельную конфигурацию вынесем, так ьудет больше порядка как мне кажется :)

```
@Configuration 
public class MapperConfig {

    @Bean
    public ModelMapper modelMapper() {
     ....
    }
}
```

2022-10-10 11:14 UTC, eugene-lenkevich commented on stat-service/src/main/java/ru/practicum/explorewithme/stat/repository/StatRepository.java
> +    @Query(nativeQuery = true, name = "find_view_stats_with_unique_ip")
Статистика нативными запросами - неплохое решение, они могут быть достаточно сложными, проще и эффективнее на sql бывает их сделать, просто к слову :)

2022-10-10 19:35 UTC, kompasvideo commented on main-service/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
удалил

2022-10-10 19:36 UTC, kompasvideo commented on main-service/src/main/java/ru/practicum/explorewithme/main/category/CategoryRepository.java
> +    Category findCategoryById(Long id);
удалил метод в интерфейсе
заменил на findById(id) в сервисе

2022-10-10 19:36 UTC, kompasvideo commented on main-service/src/main/java/ru/practicum/explorewithme/main/category/CategoryServiceImpl.java
> +        categoryRepository.findById(categoryDto.getId()).orElseThrow(() ->
заменил

2022-10-10 20:00 UTC, kompasvideo commented on main-service/src/main/java/ru/practicum/explorewithme/main/compilation/CompilationEventRepository.java
> +    Boolean existsByEventCompilationId(Long eventId, Long compId);
не нашлось 
есть только existsById

2022-10-10 20:52 UTC, kompasvideo commented on main-service/src/main/java/ru/practicum/explorewithme/main/event/model/AdminUpdateEventDto.java
> +    @JsonSerialize(using = LocalDateTimeSerializer.class)
получилось

2022-10-11 04:49 UTC, eugene-lenkevich commented on main-service/src/main/java/ru/practicum/explorewithme/main/compilation/CompilationEventRepository.java
> +    Boolean existsByEventCompilationId(Long eventId, Long compId);
> не нашлось есть только existsById

метод можно ж свой написать, подобную строчку добавить и все :)

2022-10-11 14:23 UTC, kompasvideo commented on main-service/src/main/java/ru/practicum/explorewithme/main/request/RequestServiceImpl.java
> +        userRepository.findById(userId).orElseThrow(() -> new NotFoundException(userId.toString()));
заменил на existsById

2022-10-11 17:33 UTC, kompasvideo commented on main-service/src/main/java/ru/practicum/explorewithme/main/request/RequestRepository.java
> +    Boolean existsByEventIdAndUserId(Long userId, Long eventId);
заменил на 
Boolean existsByRequesterAndEvent(Long userId, Long eventId);

2022-10-11 18:41 UTC, kompasvideo commented on main-service/src/main/java/ru/practicum/explorewithme/main/compilation/CompilationEventRepository.java
> +    Boolean existsByEventCompilationId(Long eventId, Long compId);
да, всё сделал

2022-10-11 18:51 UTC, kompasvideo commented on stat-service/src/main/java/ru/practicum/explorewithme/stat/StatService.java
> +    public ModelMapper modelMapper() {
вынес в класс MapperConfig

2022-10-11 21:15 UTC, kompasvideo commented on stat-module/src/main/java/ru/practicum/explorewithme/statmodule/ClientStat.java
> +        HttpEntity<StatData> httpEntity = new HttpEntity<>(StatData.builder()
У меня клиент  в отдельном модуле, который входит и в сервис статистики и главный сервис
https://disk.yandex.ru/d/c8QRbA_0vv9ugQ/02%20-%20Артур%20Домбровский%20/Q%26A_2022-09-27.mp4
В этом видео Артур Домбровский просил сделать клиент и dto в отдельном модуле, чтоб при чтении статистики из главного сервиса можно было импортировать не весь сервис статистики а модуль где dto

2022-10-11 21:23 UTC, kompasvideo commented on stat-service/src/main/java/ru/practicum/explorewithme/stat/repository/StatRepository.java
> +    @Query(nativeQuery = true, name = "find_view_stats_with_unique_ip")
принято

2022-10-12 04:35 UTC, eugene-lenkevich commented on stat-module/src/main/java/ru/practicum/explorewithme/statmodule/ClientStat.java
> +        HttpEntity<StatData> httpEntity = new HttpEntity<>(StatData.builder()
Ну это немножко уже про другое, а в целом все верно, контракты вэб-сервса, в т.ч клиенты, оформляются отдельным модулем и другие сервисы импортируя эти контракты делают к нему запросы

2022-10-12 04:55 UTC, eugene-lenkevich approved these changes
Привет, Андрей, спасибо за ПР, как по мне очень даже симпатично все получилось, спасибо!

2022-10-12 04:55 UTC, eugene-lenkevich commented on main-service/src/main/java/ru/practicum/explorewithme/main/request/RequestServiceImpl.java
> +        if (!requestRepository.existsById(requestId))
Тут подумал.
Эти запросы можно было  объединить, достаточно из репозитория возвращать Optional<Request>

```
       if (!requestRepository.existsById(requestId))
            throw new NotFoundException("NotFoundException RequestServiceImpl cancel, requestId: " + requestId);

        Request requestDto = requestRepository.getReferenceById(requestId);
```
получилось бы вот такой код

` Request requestDto = requestRepository.getById(requestId).orElseThrow(...)`

или даже еще более оптимально с точки зрения запросов к БД

` Request requestDto = requestRepository.findByIdAndRequesterId(requestId, userId).orElseThrow(...)`

таким образом, если бы передали идентификатор не того пользователя, то запрос бы просто ничего не нашел. Что, кстати, с точки зрения безопасности, несколько лучше, так как мы на самом раннем этапе отсекаем всё лишнее и даем минимум информации - не понятно то ли доступа нет, то ли вообще нет таких данных.

Но это альтернативные реализации, текущая реализация тоже норм, мысли в слух :)

2022-10-12 20:57 UTC, merged